# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'practice_RxSwift_CloudFileStore' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for practice_RxSwift_CloudFileStore
  # add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'

  target 'practice_RxSwift_CloudFileStoreTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'practice_RxSwift_CloudFileStoreUITests' do
    # Pods for testing
  end

end
